# Generated by Django 4.0 on 2022-01-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=120, verbose_name='نام خانوادگی')),
                ('certificate_code', models.IntegerField(blank=True, max_length=8, unique=True, verbose_name='کد مدرک')),
                ('qr_code', models.ImageField(blank=True, upload_to='', verbose_name='کیو آر کد ')),
            ],
        ),
    ]
