# Generated by Django 4.0 on 2022-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, unique=True, verbose_name='کد مدرک'),
        ),
    ]
