# Generated by Django 4.0 on 2022-01-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QrcodeCreator', '0002_alter_certificate_certificate_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
