# Generated by Django 4.0 on 2021-12-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام یادداشت')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('do_date', models.DateTimeField(verbose_name='تاریخ ایجاد')),
                ('is_do', models.BooleanField(default=False, verbose_name='انجام شده یا نشده ')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
