# Generated by Django 4.0 on 2022-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='do_date',
            field=models.DateTimeField(verbose_name='تاریخ انجام '),
        ),
    ]
