# Generated by Django 4.0 on 2022-02-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todo_update_date_alter_todo_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('is_do',)},
        ),
    ]
